name: cached_network_image_web
description: Web implementation of CachedNetworkImage
version: 1.0.3
homepage: https://github.com/Baseflow/flutter_cached_network_image
environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.1
  cached_network_image_platform_interface: ^2.0.1

dev_dependencies:
  file: '>=6.1.4 <8.0.0'
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
