name: cached_network_image
description: Flutter library to load and cache network images.
  Can also be used with placeholder and error widgets.
homepage: https://github.com/Baseflow/flutter_cached_network_image
topics:
  - cache
  - image
  - network-image
version: 3.2.4
environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_cache_manager:
    git:
      url: https://github.com/Carapacik/flutter_cache_manager.git
      path: flutter_cache_manager
  octo_image: ^1.0.2
  cached_network_image_platform_interface:
    git:
      url: https://github.com/Carapacik/flutter_cached_network_image.git
      path: cached_network_image_platform_interface
      ref: actual
  cached_network_image_web:
    git:
      url: https://github.com/Carapacik/flutter_cached_network_image.git
      path: cached_network_image_web
      ref: actual

dev_dependencies:
  file: '>=6.1.4 <8.0.0'
  flutter_lints: ^2.0.2
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
