name: cached_network_image
description: Flutter library to load and cache network images.
  Can also be used with placeholder and error widgets.
homepage: https://github.com/Baseflow/flutter_cached_network_image
version: 3.3.0
environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.4.0
  octo_image: ^1.0.2
  cached_network_image_platform_interface: ^2.1.0
  cached_network_image_web: ^1.1.0

dev_dependencies:
  file: '>=6.0.0 <8.0.0'
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
